const menu = [
    {
      id: 1,
      title: 'North Indian',
      category: 'breakfast',
      price: 199,
      img: './images/item-1.jpeg',
      desc: `"Indian Food" is the blanket term given to the wide variety of cuisines the Indian subcontinent offe...`,
    },
    {
      id: 2,
      title: 'Burgurs and  Fries',
      category: 'lunch',
      price: 250,
      img: './images/item-2.jpeg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'milkshake',
      category: 'shakes',
      price: 259,
      img: './images/item-3.jpeg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'South Indian',
      category: 'breakfast',
      price: 199,
      img: './images/item-4.jpeg',
      desc: `South India including Pongal, Masala dosa, Chicken 65, Sambar, Pulihora, Appam, Upma, Hyderabadi biryani and many more. `,
    },
    {
      id: 5,
      title: 'egg omlete',
      category: 'lunch',
      price: 50,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Chocklate Shake',
      category: 'shakes',
      price: 200,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Continental',
      category: 'breakfast',
      price: 200,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Burgurs',
      category: 'lunch',
      price: 300,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Shake',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;